name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install


  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: npm test


  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Simulate deployment
        run: echo "Deploying application..."


  notify-email:
    runs-on: ubuntu-latest
    needs: [build, test, deploy]
    if: always()

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: >
            ${{ job.status == 'success' && '✅ SUCCESS' || '❌ FAILURE' }} - CI/CD Pipeline
          body: |
            Pipeline Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.EMAIL_TO }}
          from: CI/CD Bot